/// <reference types="vite/client" />

declare const __VERSION__: string;
declare const __RELEASE__: string;
declare const __SENTRY_DSN__: string;
declare const __SENTRY_ENVIRONMENT__: string;
declare const __SITE_ID__: string;
declare const __SITE_TITLE__: string;
declare const __SITE_DESCRIPTION__: string;
declare const __SITE_URL__: string;
declare const __TIMESTAMP__: string;
declare const __HUMANS_WORD_CURATOR__: string;
declare const __HUMANS_DEVELOPER_NAME__: string;
declare const __HUMANS_DEVELOPER_CONTACT__: string;
declare const __HUMANS_DEVELOPER_SITE__: string;
declare const __COLOR_PRIMARY__: string;
declare const __COLOR_PRIMARY_LIGHT__: string;
declare const __COLOR_PRIMARY_DARK__: string;
declare const __ENVIRONMENT__: string;
declare const __GA_MEASUREMENT_ID__: string;
declare const __GA_ENABLED__: boolean;
declare const __SHOW_EMPTY_STATS__: boolean;
declare const __SOURCE_DIR__: string;
declare const __WORD_DATA_PATH__: string;
